@host = http://localhost:5151


POST {{host}}/auth/Register
Content-Type: application/json

{
  "firstName": "Himanshu",
  "lastName": "Saini",
  "email": "himanshusaini0345@outlook.com",
  "password": "him123"
}



